language: python

sudo: false

services:
  - mongodb

env:
    - PYTHON="3.5"
    - PYTHON="3.6"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - travis_retry conda create --yes -n test python=$PYTHON --file requirements.txt
    - source activate test
    - conda install --yes --file requirements-dev.txt;

before_script:
    - python run_examples.py &

script:
    - find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100
    - python setup.py test
